"""baseline

Revision ID: 0001
Revises: 
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('task', postgresql.ENUM('text_classification', 'token_classification', 'text_generation', 'question_answering', 'summarization', 'sequence_to_sequence', 'text_embedding', 'image_classification', 'object_detection', 'image_segmentation', 'image_captioning', 'audio_classification', 'automatic_speech_recognition', 'audio_segmentation', 'audio_captioning', 'tabular_regression', 'tabular_classification', 'tabular_clustering', 'tabular_anomaly_detection', name='project_task'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('modality', postgresql.ENUM('text', 'vision', 'audio', 'tabular', name='modality'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('dataset_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'content_hash', name='dataset_items_datasetId_contentHash_key')
    )
    op.create_index(op.f('ix_dataset_items_dataset_id'), 'dataset_items', ['dataset_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'building', 'ready', 'failed', name='dataset_version_status'), server_default='draft', nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('class_count', sa.Integer(), nullable=True),
    sa.Column('parquet_key', sa.Text(), nullable=True),
    sa.Column('failed_message', sa.Text(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_tag', name='datasetVersions_datasetId_versionTag_key')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_table('label_classes',
    sa.Column('class_id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ui_color_hex', sa.String(length=7), server_default='#FFFFFF', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('dataset_id', 'name', name='labelClasses_datasetId_name_key')
    )
    op.create_index(op.f('ix_label_classes_dataset_id'), 'label_classes', ['dataset_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('annotator_id', sa.String(length=100), nullable=True),
    sa.Column('annotation_type', postgresql.ENUM('classification', 'bounding_box', 'segmentation_mask', 'text_sequence', 'token_tags', 'preference_rank', name='annotation_type'), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('label_text_sequence', sa.Text(), nullable=True),
    sa.Column('label_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence_score BETWEEN 0.0 AND 1.0', name='confidence_bounds'),
    sa.ForeignKeyConstraint(['class_id'], ['label_classes.class_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('annotations_item_classification_key', 'annotations', ['item_id'], unique=True, postgresql_where=sa.text("annotation_type = 'classification'"))
    op.create_index('idx_annotations_class', 'annotations', ['class_id', 'annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_annotation_type'), 'annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_item_id'), 'annotations', ['item_id'], unique=False)
    op.create_table('audio_features',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), server_default='1', nullable=True),
    sa.Column('audio_codec', postgresql.ENUM('wav', 'mp3', 'flac', 'ogg', name='audio_codec'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('dataset_version_items',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('split_type', postgresql.ENUM('train', 'test', 'validation', name='split_type'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'item_id')
    )
    op.create_index('datasetVersionItems_versionId_splitType_idx', 'dataset_version_items', ['version_id', 'split_type'], unique=False)
    op.create_table('sweeps',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('search_space', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy', postgresql.ENUM('grid', 'random', name='sweep_strategy'), nullable=False),
    sa.Column('max_trials', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('running', 'completed', 'canceled', name='sweep_status'), server_default='running', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sweeps_project_id'), 'sweeps', ['project_id'], unique=False)
    op.create_table('tabular_features',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_tabular_features_gin', 'tabular_features', ['features_json'], unique=False, postgresql_using='gin')
    op.create_table('text_features',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_text_features_language_code'), 'text_features', ['language_code'], unique=False)
    op.create_table('vision_features',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), server_default='3', nullable=True),
    sa.Column('image_format', postgresql.ENUM('jpeg', 'png', name='image_format'), nullable=True),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['dataset_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'succeeded', 'failed', 'canceled', name='training_status'), server_default='queued', nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('sweep_id', sa.Uuid(), nullable=True),
    sa.Column('trial_index', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ludwig_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_key', sa.Text(), nullable=True),
    sa.Column('best_epoch', sa.Integer(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sweep_id'], ['sweeps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_project_id'), 'training_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_training_runs_status'), 'training_runs', ['status'], unique=False)
    op.create_index(op.f('ix_training_runs_sweep_id'), 'training_runs', ['sweep_id'], unique=False)
    op.create_table('exports',
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier', postgresql.ENUM('model', 'devkit', 'app', name='export_tier'), nullable=False),
    sa.Column('format', postgresql.ENUM('onnx', 'torchscript', name='export_format'), nullable=False),
    sa.Column('lang', postgresql.ENUM('python', 'typescript', 'csharp', 'java', 'pwa', 'flutter', name='export_lang'), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'converting', 'assembling', 'ready', 'failed', name='export_status'), server_default='pending', nullable=False),
    sa.Column('bundle_key', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.CHAR(length=64), nullable=True),
    sa.Column('failed_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_run_id'), 'exports', ['run_id'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_table('inference_jobs',
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', name='inference_job_status'), server_default='pending', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('upload_key', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_jobs_run_id'), 'inference_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_inference_jobs_status'), 'inference_jobs', ['status'], unique=False)
    op.create_table('run_evaluations',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('success', 'failed', name='evaluation_status'), nullable=False),
    sa.Column('split', postgresql.ENUM('train', 'test', 'validation', 'full', name='evaluation_split'), nullable=True),
    sa.Column('report_key', sa.Text(), nullable=True),
    sa.Column('predictions_key', sa.Text(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accuracy', sa.REAL(), nullable=True),
    sa.Column('macro_f1', sa.REAL(), nullable=True),
    sa.Column('failed_message', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('run_events',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', postgresql.ENUM('status', 'metric', 'log', name='run_event_kind'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index('run_events_run_id_seq_idx', 'run_events', ['run_id', 'seq'], unique=False)
    op.create_table('training_metrics',
    sa.Column('training_run_id', sa.Uuid(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('split', postgresql.ENUM('train', 'test', 'validation', name='split_type'), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_run_id', 'epoch', 'split', 'metric_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_metrics')
    op.drop_index('run_events_run_id_seq_idx', table_name='run_events')
    op.drop_table('run_events')
    op.drop_table('run_evaluations')
    op.drop_index(op.f('ix_inference_jobs_status'), table_name='inference_jobs')
    op.drop_index(op.f('ix_inference_jobs_run_id'), table_name='inference_jobs')
    op.drop_table('inference_jobs')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_run_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_training_runs_sweep_id'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_status'), table_name='training_runs')
    op.drop_index(op.f('ix_training_runs_project_id'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_table('vision_features')
    op.drop_index(op.f('ix_text_features_language_code'), table_name='text_features')
    op.drop_table('text_features')
    op.drop_index('idx_tabular_features_gin', table_name='tabular_features', postgresql_using='gin')
    op.drop_table('tabular_features')
    op.drop_index(op.f('ix_sweeps_project_id'), table_name='sweeps')
    op.drop_table('sweeps')
    op.drop_index('datasetVersionItems_versionId_splitType_idx', table_name='dataset_version_items')
    op.drop_table('dataset_version_items')
    op.drop_table('audio_features')
    op.drop_index(op.f('ix_annotations_item_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_annotation_type'), table_name='annotations')
    op.drop_index('idx_annotations_class', table_name='annotations')
    op.drop_index('annotations_item_classification_key', table_name='annotations', postgresql_where=sa.text("annotation_type = 'classification'"))
    op.drop_table('annotations')
    op.drop_index(op.f('ix_label_classes_dataset_id'), table_name='label_classes')
    op.drop_table('label_classes')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_dataset_items_dataset_id'), table_name='dataset_items')
    op.drop_table('dataset_items')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    # ### end Alembic commands ###
