import { writeFile } from 'node:fs/promises'
import { $ } from 'bun'
import { compiledSchemas } from './lib/schema'
import { STREAM_DEFS, SUBJECT_TEMPLATES, SUBJECT_WILDCARDS } from './lib/subjects'

const compileSchema = async <T>(schema: T, name: string) => {
  await writeFile(`./schema/${name}.json`, JSON.stringify(schema, null, 2))
  await $`uv run --project ai_service datamodel-codegen --input schema/${name}.json --output ai_service/schema/${name}.py \
    --input-file-type jsonschema \
    --output-model-type pydantic_v2.BaseModel \
    --use-type-alias \
    --enum-field-as-literal all \
    --target-python-version 3.12 \
    --use-annotated \
    --formatters builtin \
    --naming-strategy parent-prefixed \
    --snake-case-field \
    --alias-generator to_camel \
    --allow-population-by-field-name`
}

for (const [schema, name] of compiledSchemas) {
  await compileSchema(schema, name)
}

async function compileSubjects() {
  await writeFile(
    './schema/subjects.json',
    JSON.stringify(
      {
        templates: SUBJECT_TEMPLATES,
        wildcards: SUBJECT_WILDCARDS,
        streams: STREAM_DEFS,
      },
      null,
      2,
    ),
  )

  const pyDict = (obj: Record<string, string>) =>
    Object.entries(obj)
      .map(([k, v]) => `    "${k}": "${v}",`)
      .join('\n')

  const pyStreams = STREAM_DEFS.map((s) => {
    const fields = [
      `"name": "${s.name}"`,
      `"subjects": [${s.subjects.map((sub) => `"${sub}"`).join(', ')}]`,
      `"retention": "${s.retention}"`,
      `"max_age_seconds": ${s.maxAgeSeconds}`,
      ...(s.maxMsgsPerSubject !== undefined ? [`"max_msgs_per_subject": ${s.maxMsgsPerSubject}`] : []),
    ]
    return `    {\n        ${fields.join(',\n        ')},\n    },`
  }).join('\n')

  const py = `# generated by server/compile_schema.ts from server/lib/subjects.ts
# do not edit by hand — edit the TS source and re-run
#   \`bun run server/compile_schema.ts\`

from typing import Final, TypedDict


class StreamDef(TypedDict, total=False):
    name: str
    subjects: list[str]
    retention: str
    max_age_seconds: int
    max_msgs_per_subject: int


SUBJECT_TEMPLATES: Final[dict[str, str]] = {
${pyDict(SUBJECT_TEMPLATES)}
}

SUBJECT_WILDCARDS: Final[dict[str, str]] = {
${pyDict(SUBJECT_WILDCARDS)}
}

STREAMS: Final[list[StreamDef]] = [
${pyStreams}
]


def train_task(run_id: str) -> str:
    return SUBJECT_TEMPLATES["trainTask"].format(runId=run_id)


def export_task(job_id: str) -> str:
    return SUBJECT_TEMPLATES["exportTask"].format(jobId=job_id)


def abort_command(run_id: str) -> str:
    return SUBJECT_TEMPLATES["abortCommand"].format(runId=run_id)


def run_event(run_id: str, kind: str) -> str:
    return SUBJECT_TEMPLATES["runEvent"].format(runId=run_id, kind=kind)


def run_events_wildcard(run_id: str) -> str:
    return SUBJECT_TEMPLATES["runEventsWildcard"].format(runId=run_id)


def inference_task(inference_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceTask"].format(inferenceId=inference_id)


def inference_warm(run_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceWarm"].format(runId=run_id)


def inference_result(inference_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceResult"].format(inferenceId=inference_id)


def dlq(kind: str, id: str) -> str:
    return SUBJECT_TEMPLATES["dlq"].format(kind=kind, id=id)


def abort_flag(run_id: str) -> str:
    return SUBJECT_TEMPLATES["abortFlag"].format(runId=run_id)
`

  await writeFile('./ai_service/schema/subjects.py', py)
}

await compileSubjects()
