# generated by datamodel-codegen:
#   filename:  command.json
#   timestamp: 2026-09-01T03:38:32+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class Command(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    command: Literal['abort']
    run_id: UUID
