# generated by datamodel-codegen:
#   filename:  export_task.json
#   timestamp: 2026-08-04T16:11:26+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class ExportTask(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    job_id: UUID
    run_id: UUID
    format: Literal['onnx', 'torchscript']
