# generated by datamodel-codegen:
#   filename:  inference_request.json
#   timestamp: 2026-08-04T16:11:26+00:00

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class InferenceRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    run_id: UUID
    upload_key: str
    upload_filename: str
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
