# generated by datamodel-codegen:
#   filename:  inference_response.json
#   timestamp: 2026-09-01T03:38:31+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class InferenceResponseInferenceResponseOutputClass(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    label: str
    confidence: float


class InferenceResponseInferenceResponseOutput(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['classification']
    feature: str
    classes: list[InferenceResponseInferenceResponseOutputClass]


class InferenceResponseInferenceResponseOutput1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['regression']
    feature: str
    value: float


class InferenceResponseInferenceResponseOutput2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['text']
    feature: str
    text: str


class InferenceResponseInferenceResponseOutput3Token(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    token: str
    tag: str


class InferenceResponseInferenceResponseOutput3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['tokens']
    feature: str
    tokens: list[InferenceResponseInferenceResponseOutput3Token]


class InferenceResponseInferenceResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    status: Literal['success']
    run_id: UUID
    output: InferenceResponseInferenceResponseOutput | InferenceResponseInferenceResponseOutput1 | InferenceResponseInferenceResponseOutput2 | InferenceResponseInferenceResponseOutput3


type InferenceResponseInferenceResponse1RowCount = Annotated[int, Field(ge=0)]


class InferenceResponseInferenceResponse1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    status: Literal['batch']
    run_id: UUID
    result_key: str
    row_count: InferenceResponseInferenceResponse1RowCount


class InferenceResponseInferenceResponse2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    status: Literal['failed']
    run_id: UUID
    error: str


type InferenceResponse = Annotated[
    InferenceResponseInferenceResponse | InferenceResponseInferenceResponse1 | InferenceResponseInferenceResponse2,
    Field(title='InferenceResponse'),
]
