# generated by datamodel-codegen:
#   filename:  inference_task.json
#   timestamp: 2026-09-01T03:38:30+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr
from pydantic.alias_generators import to_camel

type InferenceTaskTopK = Annotated[int, Field(ge=1, le=1000)]


class InferenceTaskPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['file']
    upload_key: str
    upload_filename: str


class InferenceTaskPayload1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['text']
    fields: dict[constr(pattern=r'^(.*)$'), str]


class InferenceTaskPayload2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['record']
    record: dict[constr(pattern=r'^(.*)$'), str | float]


class InferenceTaskPayload3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['batch']
    upload_key: str
    upload_filename: str


class InferenceTask(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    inference_id: UUID
    run_id: UUID
    top_k: InferenceTaskTopK | None = 100
    payload: InferenceTaskPayload | InferenceTaskPayload1 | InferenceTaskPayload2 | InferenceTaskPayload3
