# generated by datamodel-codegen:
#   filename:  inference_request.json
#   timestamp: 2026-08-14T02:57:34+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr
from pydantic.alias_generators import to_camel


class InferenceRequestPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['file']
    upload_key: str
    upload_filename: str


class InferenceRequestPayload1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['text']
    text: str


class InferenceRequestPayload2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['record']
    record: dict[constr(pattern=r'^(.*)$'), str | float]


class InferenceRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    run_id: UUID
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
    payload: InferenceRequestPayload | InferenceRequestPayload1 | InferenceRequestPayload2
