# generated by datamodel-codegen:
#   filename:  run_event.json
#   timestamp: 2026-08-14T02:57:35+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr
from pydantic.alias_generators import to_camel


class RunEventRunEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['status']
    run_id: UUID
    ts: AwareDatetime
    status: Literal['queued', 'running', 'succeeded', 'failed', 'canceled']
    message: str | None = None


type RunEventRunEvent1Epoch = Annotated[int, Field(ge=0)]


class RunEventRunEvent1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['metric']
    run_id: UUID
    ts: AwareDatetime
    epoch: RunEventRunEvent1Epoch
    split: Literal['train', 'test', 'validation']
    metrics: dict[constr(pattern=r'^(.*)$'), float]


class RunEventRunEvent2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['log']
    run_id: UUID
    ts: AwareDatetime
    level: Literal['info', 'warn', 'error']
    line: str


class RunEventRunEvent3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    kind: Literal['export']
    run_id: UUID
    ts: AwareDatetime
    job_id: UUID
    status: Literal['success', 'failed']
    format: Literal['onnx', 'torchscript'] | None = 'onnx'
    export_key: str | None = None
    error: str | None = None


type RunEvent = Annotated[
    RunEventRunEvent | RunEventRunEvent1 | RunEventRunEvent2 | RunEventRunEvent3,
    Field(title='RunEvent'),
]
