# generated by server/compile_schema.ts from server/lib/subjects.ts
# do not edit by hand — edit the TS source and re-run
#   `bun run server/compile_schema.ts`

from typing import Final, TypedDict


class StreamDef(TypedDict, total=False):
    name: str
    subjects: list[str]
    retention: str
    max_age_seconds: int
    max_msgs_per_subject: int


SUBJECT_TEMPLATES: Final[dict[str, str]] = {
    "trainTask": "theseus.task.train.{runId}",
    "exportTask": "theseus.task.export.{jobId}",
    "abortCommand": "theseus.command.run.{runId}",
    "runEvent": "theseus.event.run.{runId}.{kind}",
    "runEventsWildcard": "theseus.event.run.{runId}.>",
    "inferenceTask": "theseus.task.inference.{inferenceId}",
    "inferenceWarm": "theseus.inference.warm.{runId}",
    "inferenceResult": "theseus.inference.result.{inferenceId}",
    "dlq": "theseus.dlq.{kind}.{id}",
    "abortFlag": "theseus.abortflag.{runId}",
}

SUBJECT_WILDCARDS: Final[dict[str, str]] = {
    "tasks": "theseus.task.>",
    "events": "theseus.event.>",
    "allRunEvents": "theseus.event.run.*.>",
    "commands": "theseus.command.>",
    "dlq": "theseus.dlq.>",
    "abortFlags": "theseus.abortflag.>",
    "trainTasks": "theseus.task.train.*",
    "exportTasks": "theseus.task.export.*",
    "inferenceTasks": "theseus.task.inference.*",
    "commandsPerRun": "theseus.command.run.*",
    "inferenceWarmAll": "theseus.inference.warm.*",
    "inferenceResultsAll": "theseus.inference.result.*",
}

STREAMS: Final[list[StreamDef]] = [
    {
        "name": "THESEUS_TASKS",
        "subjects": ["theseus.task.>"],
        "retention": "workqueue",
        "max_age_seconds": 86400,
    },
    {
        "name": "THESEUS_EVENTS",
        "subjects": ["theseus.event.>"],
        "retention": "limits",
        "max_age_seconds": 604800,
    },
    {
        "name": "THESEUS_COMMANDS",
        "subjects": ["theseus.command.>"],
        "retention": "workqueue",
        "max_age_seconds": 3600,
    },
    {
        "name": "THESEUS_DLQ",
        "subjects": ["theseus.dlq.>"],
        "retention": "limits",
        "max_age_seconds": 2592000,
    },
    {
        "name": "THESEUS_ABORT_FLAGS",
        "subjects": ["theseus.abortflag.>"],
        "retention": "limits",
        "max_age_seconds": 604800,
        "max_msgs_per_subject": 1,
    },
    {
        "name": "THESEUS_INFERENCE_RESULTS",
        "subjects": ["theseus.inference.result.*"],
        "retention": "limits",
        "max_age_seconds": 3600,
        "max_msgs_per_subject": 1,
    },
]


def train_task(run_id: str) -> str:
    return SUBJECT_TEMPLATES["trainTask"].format(runId=run_id)


def export_task(job_id: str) -> str:
    return SUBJECT_TEMPLATES["exportTask"].format(jobId=job_id)


def abort_command(run_id: str) -> str:
    return SUBJECT_TEMPLATES["abortCommand"].format(runId=run_id)


def run_event(run_id: str, kind: str) -> str:
    return SUBJECT_TEMPLATES["runEvent"].format(runId=run_id, kind=kind)


def run_events_wildcard(run_id: str) -> str:
    return SUBJECT_TEMPLATES["runEventsWildcard"].format(runId=run_id)


def inference_task(inference_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceTask"].format(inferenceId=inference_id)


def inference_warm(run_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceWarm"].format(runId=run_id)


def inference_result(inference_id: str) -> str:
    return SUBJECT_TEMPLATES["inferenceResult"].format(inferenceId=inference_id)


def dlq(kind: str, id: str) -> str:
    return SUBJECT_TEMPLATES["dlq"].format(kind=kind, id=id)


def abort_flag(run_id: str) -> str:
    return SUBJECT_TEMPLATES["abortFlag"].format(runId=run_id)
