# generated by datamodel-codegen:
#   filename:  train_task.json
#   timestamp: 2026-09-01T03:38:29+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class TrainTask(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_camel,
    )
    run_id: UUID
    project_id: UUID
    dataset_version_id: UUID
    config_key: str
    dataset_key: str
    output_prefix: str
