# generated by datamodel-codegen:
#   filename:  training.json
#   timestamp: 2026-06-23T03:18:22+00:00

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, Field


class LudwigTrainingConfiguration(BaseModel):
    run_id: Annotated[UUID, Field(alias='runId', description='The run ID')]
    dataset_version_id: Annotated[
        UUID, Field(alias='datasetVersionId', description='The dataset version ID')
    ]
