# generated by datamodel-codegen:
#   filename:  training.json
#   timestamp: 2026-06-23T02:55:32+00:00

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, Field


class LudwigTrainingConfigurationDataset(BaseModel):
    project_id: Annotated[UUID, Field(alias='projectId', description='The project ID')]
    version_id: Annotated[
        UUID, Field(alias='versionId', description='The dataset version ID')
    ]


class LudwigTrainingConfiguration(BaseModel):
    run_id: Annotated[UUID, Field(alias='runId', description='The run ID')]
    dataset: LudwigTrainingConfigurationDataset
