"""Task registry: the single source of truth for every trainable task.

Ported from server/lib/tasks/{registry,types,index}.ts. It drives project creation, upload
validation, snapshot column derivation, Ludwig config compilation, inference request/response
shapes and export READMEs on the backend, and (via schema/task_registry.json, generated by
scripts/export_schema.py) the task picker and per-modality UI on the frontend.

Adding a trainable task is one entry here, not five edits.

Feature lists are static data. The TypeScript version modelled them as functions of a snapshot
context, but no task ever read that context, and the tabular tasks return an empty list because
their input columns are dataset-defined (the compiler derives those from the snapshot instead).
"""

from dataclasses import dataclass, field
from typing import Any, Literal

from theseus import constants as C
from theseus.db.enums import AnnotationType, DatasetModality, ProjectTask
from theseus.schemas.common import ApiModel

LudwigFeatureType = Literal["image", "text", "audio", "number", "category", "binary", "sequence", "vector"]

# A common, dependency-free subset of Ludwig optimizers (none need bitsandbytes).
LUDWIG_OPTIMIZER_TYPES = ("adam", "adamw", "sgd", "rmsprop", "adagrad")

ColumnKind = Literal[
    "storage_uri", "inline_text", "label", "text_sequence_label", "split", "split_index", "scalar", "item_id"
]
InferenceOutputKind = Literal["classification", "regression", "text", "tokens"]


class ColumnSpec(ApiModel):
    """A column the snapshot builder writes into a version dataset.parquet, in order."""

    name: str
    kind: ColumnKind


class ItemSpec(ApiModel):
    """What one dataset item carries. Drives upload, validation and the pool UI."""

    payload: Literal["file", "inline_text", "record"]
    accept: list[str] | None = None


class AnnotationSpec(ApiModel):
    """Ground truth shape. Drives the Classes page and annotation editors."""

    type: AnnotationType
    requires_label_classes: bool


class EncoderChoice(ApiModel):
    id: str
    label: str
    # Ludwig encoder type value emitted into the compiled config.
    encoder_type: str
    pretrained: bool
    # Extra Ludwig encoder params merged in verbatim (e.g. torchvision model_variant).
    params: dict[str, Any] | None = None


class IntKnob(ApiModel):
    default: int
    min: int
    max: int | None = None


class FloatKnob(ApiModel):
    default: float
    min: float
    max: float | None = None


class BatchSizeKnob(ApiModel):
    default: int | Literal["auto"]
    options: list[int | Literal["auto"]]


class TrainerKnobSpec(ApiModel):
    epochs: IntKnob
    batch_size: BatchSizeKnob
    learning_rate: FloatKnob
    early_stop_patience: IntKnob


class LudwigTaskConfig(ApiModel):
    model_type: Literal["ecd", "llm"]
    input_features: list[dict[str, Any]]
    output_features: list[dict[str, Any]]
    encoders: list[EncoderChoice]
    trainer_knobs: TrainerKnobSpec


class TaskDescriptor(ApiModel):
    id: ProjectTask
    label: str
    modality: DatasetModality
    # The extension seam: a non-Ludwig backend just needs a new value here plus its own runner.
    backend: Literal["ludwig", "unsupported"]
    status: Literal["stable", "experimental", "planned"]
    item_spec: ItemSpec
    annotation: AnnotationSpec
    # Parquet columns the snapshot builder emits, in order.
    columns: list[ColumnSpec]
    # Absent for backend "unsupported" tasks.
    ludwig: LudwigTaskConfig | None = None


@dataclass
class SnapshotContext:
    """Everything the Ludwig compiler needs to know about one dataset version."""

    columns: list[ColumnSpec] = field(default_factory=list)
    # Label class names in a stable order. Empty for non-classification tasks.
    label_class_names: list[str] = field(default_factory=list)
    # Item count per class NAME (classification only), so the compiler can build balanced
    # class_weights without a DB round trip. Keyed by name: Ludwig resolves a name-keyed dict
    # against its own vocabulary, so nothing here needs to know the index Ludwig assigns.
    class_counts: dict[str, int] | None = None


# -- Column and feature shorthands -----------------------------------------------------------

IMAGE_PATH = C.IMAGE_PATH_COLUMN_NAME
CLASS = C.CLASS_COLUMN_NAME
SPLIT = C.SPLIT_COLUMN_NAME

_AUDIO_MIME = ["audio/wav", "audio/mpeg", "audio/flac", "audio/ogg"]
_IMAGE_MIME = ["image/jpeg", "image/png"]


def _col(name: str, kind: ColumnKind) -> ColumnSpec:
    return ColumnSpec(name=name, kind=kind)


def _feat(name: str, ftype: LudwigFeatureType) -> dict[str, Any]:
    return {"name": name, "type": ftype, "column": name}


def _default_knobs() -> TrainerKnobSpec:
    return TrainerKnobSpec(
        epochs=IntKnob(default=20, min=1, max=500),
        batch_size=BatchSizeKnob(default="auto", options=[16, 32, 64, 128, 256, "auto"]),
        learning_rate=FloatKnob(default=0.001, min=0.00001, max=1),
        early_stop_patience=IntKnob(default=5, min=-1),
    )


def _llm_knobs() -> TrainerKnobSpec:
    return TrainerKnobSpec(
        epochs=IntKnob(default=3, min=1, max=50),
        batch_size=BatchSizeKnob(default=1, options=[1, 2, 4, 8, "auto"]),
        learning_rate=FloatKnob(default=0.0001, min=0.000001, max=0.01),
        early_stop_patience=IntKnob(default=3, min=-1),
    )


# -- Encoder catalogs ------------------------------------------------------------------------

VISION_ENCODERS = [
    EncoderChoice(
        id="resnet18", label="ResNet-18", encoder_type="resnet", pretrained=True, params={"model_variant": 18}
    ),
    EncoderChoice(
        id="resnet50", label="ResNet-50", encoder_type="resnet", pretrained=True, params={"model_variant": 50}
    ),
    EncoderChoice(
        id="vit_base",
        label="ViT-Base/16",
        encoder_type="vit",
        pretrained=True,
        params={"model_variant": "base_patch16_224"},
    ),
    EncoderChoice(
        id="convnext_tiny",
        label="ConvNeXt-Tiny",
        encoder_type="convnext",
        pretrained=True,
        params={"model_variant": "tiny"},
    ),
    EncoderChoice(
        id="efficientnet_b0",
        label="EfficientNet-B0",
        encoder_type="efficientnet",
        pretrained=True,
        params={"model_variant": "b0"},
    ),
    EncoderChoice(
        id="mobilenet_v3_small",
        label="MobileNetV3-Small",
        encoder_type="mobilenetv3",
        pretrained=True,
        params={"model_variant": "small"},
    ),
]

TEXT_ENCODERS = [
    EncoderChoice(id="bert", label="BERT", encoder_type="bert", pretrained=True),
    EncoderChoice(id="distilbert", label="DistilBERT", encoder_type="distilbert", pretrained=True),
    EncoderChoice(id="roberta", label="RoBERTa", encoder_type="roberta", pretrained=True),
    EncoderChoice(
        id="stacked_cnn", label="Stacked CNN (train from scratch)", encoder_type="stacked_cnn", pretrained=False
    ),
]

AUDIO_ENCODERS = [
    EncoderChoice(id="stacked_cnn", label="Stacked CNN", encoder_type="stacked_cnn", pretrained=False),
    EncoderChoice(id="rnn", label="RNN", encoder_type="rnn", pretrained=False),
    EncoderChoice(id="cnnrnn", label="CNN + RNN", encoder_type="cnnrnn", pretrained=False),
]


def _ludwig_task(
    id: ProjectTask,
    label: str,
    modality: DatasetModality,
    status: Literal["stable", "experimental"],
    item_spec: ItemSpec,
    annotation: AnnotationSpec,
    columns: list[ColumnSpec],
    *,
    inputs: list[dict[str, Any]],
    outputs: list[dict[str, Any]],
    encoders: list[EncoderChoice],
    model_type: Literal["ecd", "llm"] = "ecd",
    knobs: TrainerKnobSpec | None = None,
) -> TaskDescriptor:
    return TaskDescriptor(
        id=id,
        label=label,
        modality=modality,
        backend="ludwig",
        status=status,
        item_spec=item_spec,
        annotation=annotation,
        columns=columns,
        ludwig=LudwigTaskConfig(
            model_type=model_type,
            input_features=inputs,
            output_features=outputs,
            encoders=encoders,
            trainer_knobs=knobs or (_llm_knobs() if model_type == "llm" else _default_knobs()),
        ),
    )


def _planned(
    id: ProjectTask, label: str, modality: DatasetModality, ann: AnnotationType, needs_classes: bool
) -> TaskDescriptor:
    """Genuinely blocked, not just unbuilt: Ludwig has no bounding-box or mask output feature."""
    return TaskDescriptor(
        id=id,
        label=label,
        modality=modality,
        backend="unsupported",
        status="planned",
        item_spec=ItemSpec(payload="file"),
        annotation=AnnotationSpec(type=ann, requires_label_classes=needs_classes),
        columns=[],
    )


_CLASSIFY = AnnotationSpec(type="classification", requires_label_classes=True)
_FREE_TEXT = AnnotationSpec(type="text_sequence", requires_label_classes=False)
_INLINE = ItemSpec(payload="inline_text")
_RECORD = ItemSpec(payload="record")


def _llm_text_task(id: ProjectTask, label: str, in_cols: list[str], out_col: str) -> TaskDescriptor:
    return _ludwig_task(
        id, label, "text", "experimental", _INLINE, _FREE_TEXT,
        [*(_col(c, "inline_text") for c in in_cols), _col(out_col, "inline_text"), _col(SPLIT, "split")],
        inputs=[_feat(c, "text") for c in in_cols],
        outputs=[_feat(out_col, "text")],
        encoders=[],
        model_type="llm",
    )  # fmt: skip


def _file_caption_task(
    id: ProjectTask, label: str, modality: DatasetModality, path_col: str, out_col: str, in_type: LudwigFeatureType,
    mime: list[str], encoders: list[EncoderChoice],
) -> TaskDescriptor:  # fmt: skip
    return _ludwig_task(
        id, label, modality, "experimental", ItemSpec(payload="file", accept=mime), _FREE_TEXT,
        [_col(path_col, "storage_uri"), _col(out_col, "text_sequence_label"), _col(SPLIT, "split")],
        inputs=[_feat(path_col, in_type)],
        outputs=[_feat(out_col, "text")],
        encoders=encoders,
    )  # fmt: skip


# -- Tier 1: stable --------------------------------------------------------------------------

_TASKS: list[TaskDescriptor] = [
    _ludwig_task(
        "image_classification", "Image Classification", "vision", "stable",
        ItemSpec(payload="file", accept=_IMAGE_MIME), _CLASSIFY,
        [_col(IMAGE_PATH, "storage_uri"), _col(CLASS, "label"), _col(SPLIT, "split")],
        inputs=[_feat(IMAGE_PATH, "image")], outputs=[_feat(CLASS, "category")], encoders=VISION_ENCODERS,
    ),
    _ludwig_task(
        "text_classification", "Text Classification", "text", "stable", _INLINE, _CLASSIFY,
        [_col("text", "inline_text"), _col(CLASS, "label"), _col(SPLIT, "split")],
        inputs=[_feat("text", "text")], outputs=[_feat(CLASS, "category")], encoders=TEXT_ENCODERS,
    ),
    # Tabular input columns are dataset-defined, so input_features is empty here and the
    # compiler derives one number feature per scalar column of the snapshot.
    _ludwig_task(
        "tabular_classification", "Tabular Classification", "tabular", "stable", _RECORD, _CLASSIFY,
        [_col(CLASS, "label"), _col(SPLIT, "split")],
        inputs=[], outputs=[_feat(CLASS, "category")], encoders=[],
    ),
    _ludwig_task(
        "tabular_regression", "Tabular Regression", "tabular", "stable", _RECORD,
        AnnotationSpec(type="classification", requires_label_classes=False),
        [_col("target", "label"), _col(SPLIT, "split")],
        inputs=[], outputs=[_feat("target", "number")], encoders=[],
    ),
    _ludwig_task(
        "audio_classification", "Audio Classification", "audio", "stable",
        ItemSpec(payload="file", accept=_AUDIO_MIME), _CLASSIFY,
        [_col("audio_path", "storage_uri"), _col(CLASS, "label"), _col(SPLIT, "split")],
        inputs=[_feat("audio_path", "audio")], outputs=[_feat(CLASS, "category")], encoders=AUDIO_ENCODERS,
    ),
    # -- Tier 2: experimental (Ludwig llm model type / sequence output) --
    _ludwig_task(
        "token_classification", "Token Classification", "text", "experimental", _INLINE,
        AnnotationSpec(type="token_tags", requires_label_classes=True),
        [_col("text", "inline_text"), _col("tags", "label"), _col(SPLIT, "split")],
        inputs=[_feat("text", "sequence")], outputs=[_feat("tags", "sequence")], encoders=TEXT_ENCODERS,
    ),
    _llm_text_task("text_generation", "Text Generation", ["prompt"], "completion"),
    _llm_text_task("summarization", "Summarization", ["document"], "summary"),
    _llm_text_task("sequence_to_sequence", "Sequence to Sequence", ["source"], "target"),
    _llm_text_task("question_answering", "Question Answering", ["context", "question"], "answer"),
    # -- Tier 3: experimental (file input + free-text output, Ludwig ECD) --
    _file_caption_task(
        "image_captioning", "Image Captioning", "vision", IMAGE_PATH, "caption", "image", _IMAGE_MIME, VISION_ENCODERS
    ),
    _file_caption_task(
        "audio_captioning", "Audio Captioning", "audio", "audio_path", "caption", "audio", _AUDIO_MIME, AUDIO_ENCODERS
    ),
    _file_caption_task(
        "automatic_speech_recognition", "Automatic Speech Recognition", "audio", "audio_path", "transcript", "audio",
        _AUDIO_MIME, AUDIO_ENCODERS,
    ),
    # -- Planned: no Ludwig backend at all --
    _planned("object_detection", "Object Detection", "vision", "bounding_box", True),
    _planned("image_segmentation", "Image Segmentation", "vision", "segmentation_mask", True),
    _planned("audio_segmentation", "Audio Segmentation", "audio", "segmentation_mask", True),
    _planned("tabular_clustering", "Tabular Clustering", "tabular", "classification", False),
    _planned("tabular_anomaly_detection", "Tabular Anomaly Detection", "tabular", "classification", False),
    _planned("text_embedding", "Text Embedding", "text", "classification", False),
]  # fmt: skip

TASK_REGISTRY: dict[str, TaskDescriptor] = {t.id: t for t in _TASKS}


# -- Helpers (ported from tasks/index.ts) ----------------------------------------------------


def get_task_descriptor(task: str) -> TaskDescriptor:
    return TASK_REGISTRY[task]


def task_to_modality(task: str) -> DatasetModality:
    return get_task_descriptor(task).modality


def is_classification_task(task: str | None) -> bool:
    return bool(task) and get_task_descriptor(task).annotation.requires_label_classes  # type: ignore[arg-type]


def list_selectable_tasks() -> list[TaskDescriptor]:
    """Tasks offered on project creation: only what the backend actually trains."""
    return [t for t in TASK_REGISTRY.values() if t.backend == "ludwig"]


def get_inference_input_spec(task: str) -> dict[str, Any]:
    """What an inference request must supply for this task.

    For inline_text tasks the field names come from the task Ludwig input features, so a
    multi-input task like question_answering reports both `context` and `question`.
    """
    d = get_task_descriptor(task)
    if d.item_spec.payload == "file":
        return {"kind": "file", "accept": d.item_spec.accept}
    if d.item_spec.payload == "record":
        return {"kind": "record"}
    if d.ludwig is None:
        raise ValueError(f"Task {task!r} has no Ludwig config to derive input fields from")
    return {"kind": "text", "fields": [f["column"] for f in d.ludwig.input_features]}


def get_inference_output_kind(task: str) -> InferenceOutputKind:
    """Shape of an inference response, from the first Ludwig output feature type.

    Must stay in sync with build_inference_output in services/predict.py.
    """
    d = get_task_descriptor(task)
    if d.ludwig is None:
        raise ValueError(f"Task {task!r} has no Ludwig config to derive an output kind from")
    match d.ludwig.output_features[0]["type"]:
        case "category":
            return "classification"
        case "number":
            return "regression"
        case "sequence":
            return "tokens"
        case _:
            return "text"


def registry_json() -> dict[str, Any]:
    """The frontend view of the registry (written to schema/task_registry.json).

    The two inference values are pre-evaluated so the browser needs no logic of its own.
    """
    tasks: dict[str, Any] = {}
    for task_id, d in TASK_REGISTRY.items():
        entry = d.model_dump(by_alias=True, exclude_none=True)
        if d.ludwig is not None:
            entry["inferenceInputSpec"] = get_inference_input_spec(task_id)
            entry["inferenceOutputKind"] = get_inference_output_kind(task_id)
        tasks[task_id] = entry
    return {"tasks": tasks}
